export enum CodePage {
  GENERIC_DESKTOP = 0x01,
  BUTTON_PAGE = 0x09,
}

export enum GamepadGenericDesktopPageCode {
  USAGE_AXIS_LSTICKX = 0x30, // 48
  USAGE_AXIS_LSTICKY = 0x31, // 49
  USAGE_AXIS_RSTICKX = 0x33, // 51
  USAGE_AXIS_RSTICKY = 0x34, // 52
  USAGE_AXIS_DPADX = 0x39, // 57
  USAGE_AXIS_DPADY = 0x3a, // 58
  USAGE_AXIS_RT2 = 0x32, // 50
  USAGE_AXIS_LT2 = 0x35, // 53
}

export enum GamepadButtonPageCode {
  USAGE_BTN_SIMPLE_0 = 1,
  USAGE_BTN_SIMPLE_1 = 2,
  USAGE_BTN_SIMPLE_2 = 3,
  USAGE_BTN_SIMPLE_3 = 4,
  USAGE_BTN_LT = 5,
  USAGE_BTN_RT = 6,
  USAGE_BTN_LT2 = 7,
  USAGE_BTN_RT2 = 8,
  USAGE_BTN_START = 9,
  USAGE_BTN_SELECT = 10,
  USAGE_BTN_MODE = 11,
  USAGE_BTN_DPAD_UP = 12,
  USAGE_BTN_DPAD_DOWN = 13,
  USAGE_BTN_DPAD_LEFT = 14,
  USAGE_BTN_DPAD_RIGHT = 15,
  USAGE_BTN_C = 16,
  USAGE_BTN_Z = 17,
  USAGE_BTN_LTHUMB = 18,
  USAGE_BTN_RTHUMB = 19,
}
